apiVersion: v1
kind: Secret
metadata:
  name: dcc-secrets
  namespace: devops-command-center
type: Opaque
stringData:
  database_host: postgres
  database_password: devops_secret
  jwt_access: change-me-access-secret-min-32-chars!!
  jwt_refresh: change-me-refresh-secret-min-32-chars!
  github_token: ""
  jenkins_token: ""
